### PR TITLE
Edits to slides

### PR DESCRIPTION
**Pull request by standage**
This pull request is a work in progress, not ready to be merged. I just wanted to capture what I've worked on so far. There are a few things still to be done.
- [ ] Work on transition to Noble's rules
- [x] Add section on version control
- [x] Add section on automated testing
- [x] Trim down agile vs. sturdy, focus on similarities (mention distinction in passing)
- [ ] Clean up text (current content is nice for personal notes, but too much for display)

### CODE REVIEW

**Comment by gvwilson** [comment]
Thanks @standage - I think you can assign this to me for review when it's ready, but if you can't, just drop me an email.

**Comment by standage** [comment]
Ok, I'm pretty pleased with how the slides are shaping up. In addition to the remaining tick boxes above, I'll add these.
- [ ] I'd love to include the bit about overtime. Can it still fit? Where?
- [ ] No real conclusion / resolution yet.

Ready for review and merge @gvwilson!

**Comment by standage** [comment]
Also:
- [ ] Why is the comic graphic not showing up?

**Comment by gvwilson** [comment]
The `data-markdown` attribute in the `slide` element says "interpret the content as Markdown", so the `` tag was being taken literally. (That's my guess, anyway.) I've modified to use Markdowns `text` syntax for images, and will push.

**Pull request merged**
